# Generated by Django 2.2.5 on 2019-11-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBooksKlv',
            fields=[
                ('book_number', models.IntegerField(primary_key=True, serialize=False)),
                ('korean', models.CharField(max_length=20)),
                ('k_abb', models.CharField(max_length=6)),
                ('english', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=3)),
                ('book', models.CharField(max_length=3)),
                ('chapter_count', models.IntegerField()),
            ],
            options={
                'db_table': 'bible_books_klv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bquad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_id', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('answer_start', models.IntegerField()),
            ],
            options={
                'db_table': 'bquad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KlvBible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=3)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'klv_bible',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KlvOutline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('start_id', models.IntegerField()),
                ('end_id', models.IntegerField()),
            ],
            options={
                'db_table': 'klv_outline',
                'managed': False,
            },
        ),
    ]
